#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${HOME}/.dotfiles/zprezto/init.zsh" ]]; then
  source "${HOME}/.dotfiles/zprezto/init.zsh"
fi

if [[ -f ~/.zshenv ]]; then
    source ~/.zshenv
fi

# Customized settings
if [ -f ~/.zshrc.local ]; then
    source ~/.zshrc.local
fi

# Aliases
if [ -f ~/.aliases ]; then
    source ~/.aliases
fi

# Autojump
plugins=(git autojump)
case "$OSTYPE" in
    darwin*)
        [[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh
        export PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin
        export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"
        export PATH="/usr/local/texlive/2018/bin/x86_64-darwin:$PATH"
        export GRADLE_USER_HOME=$HOME/.cache/gradle
        ;;
    linux*)
        [[ -s /usr/share/autojump/autojump.sh ]] && . /usr/share/autojump/autojump.sh
        ;;
esac
export LSCOLORS='ExHxcxdxdxGxDxabagacad'
export VISUAL=vim
export LESS="-M -R -w -X -z-4"
