#!/bin/zsh

setopt EXTENDED_GLOB

# Create vim config sym links
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
for lcfile in ${PWD}/vimrc/^*(README.md|init)*; do
    ln -s "$lcfile" "$HOME/.${lcfile:t}"
done
vim +PlugInstall +PlugClean +qa!

# Create zsh config sym links
for rcfile in "${PWD}"/zprezto/runcoms/^README.md(.N); do
    ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
done
git submodule update --init --recursive

# Create tmux.conf sym link
ln -s "${PWD}/tmux.conf" "$HOME/.tmux.conf"
git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm
