#!/bin/zsh

DOTFILESDIR=${0:h}
setopt EXTENDED_GLOB

# Create vim config sym links
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
for lcfile in ${DOTFILESDIR}/vim/rc/^*(README.md|init)*; do
    ln -s "$lcfile" "$HOME/.vim/${lcfile:t}"
done
ln -s ${DOTFILESDIR}/ycm_extra_conf.py "$HOME/.vim/ycm_extra_conf.py"
vim +PlugInstall +qa!

# Create zsh config sym links
for rcfile in "${DOTFILESDIR}"/prezto/runcoms/^README.md(.N); do
    ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
done
git submodule update --init --recursive
source $HOME/.zshrc

# Create tmux.conf sym link
ln -s "${DOTFILESDIR}/tmux.conf" "$HOME/.tmux.conf"
git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm
