#!/bin/zsh

setopt EXTENDED_GLOB

# Remove local bin sym links
if [ -s $HOME/.local ]; then
    BINDIR=$HOME/.local/bin
elif [ -s /usr/local/bin/ ]; then
    BINDIR=/usr/local/bin
else
    BINDIR=$HOME/.local/bin
fi
for xfile in ${PWD}/bin/*; do
    rm -f "$BINDIR/${xfile:t}"
done

# Remove vim files
for lcfile in ${PWD}/vim/(rc|ext)/*; do
    rm "$HOME/.vim/${lcfile:t}"
done
for lcfile in ${PWD}/vim/nvim/*; do
    rm "$HOME/.config/nvim/${lcfile:t}"
done
rm -r $HOME/.vim/tempfiles

# Remove zsh files
for rcfile in "${PWD}"/zsh/configs/*; do
    rm "$HOME/.${rcfile:t}"
done
rm -rf $HOME/.cache/.zcompdump* $HOME/.zhistory $HOME/.cache/.zcompcache

# Remove dot files
for dfile in ${PWD}/dotconf/*; do
    rm -f "$HOME/.${dfile:t}"
done
