#!/bin/zsh

setopt EXTENDED_GLOB

# Remove local bin sym links
if [ -s $HOME/.local ]; then
    BINDIR=$HOME/.local/bin
elif [ -s /usr/local/bin/ ]; then
    BINDIR=/usr/local/bin
else
    BINDIR=$HOME/.local/bin
fi
for xfile in ${PWD}/bin/; do
    rm -f "$BINDIR/${xfile:t}"
done

# Remove vim files
for lcfile in ${PWD}/vim/configs/^*(README.md|init)*; do
    rm "$HOME/.vim/${lcfile:t}"
done
rm $HOME/.vim/ycm_extra_conf.py
rm $HOME/.viminfo

# Remove zsh files
for rcfile in "${PWD}"/zsh/configs/*; do
    rm "$HOME/.${rcfile:t}"
done
rm -rf $HOME/.cache/.zcompdump* $HOME/.zhistory $HOME/.cache/.zcompcache

# Remove tmux files
rm "$HOME/.tmux.conf"
rm -rf $HOME/.tmux/

# Remove git configs
rm $HOME/.gitconfig
rm $HOME/.gitignore_global
