#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Qing Du <qdduuu@gmail.com>
#

#
# Poisson host
#
export POISSON_IP="192.168.32.77"

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

local editor='vim'
if (( $+commands[nvim] )); then
    local editor='nvim'
fi

export VISUAL=$editor
export EDITOR=$VISUAL
export PAGER='less'

#
# Language
#

if [[ -z "$LC_ALL" ]]; then
  export LANG='en_US.UTF-8'
  export LC_ALL='en_US.UTF-8'
  export LC_CTYPE='UTF-8'
fi

#
# Paths
#

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
case "$OSTYPE" in
    darwin*)
        path=(
            /usr/local/opt/llvm/bin
            /usr/local/{texlive/2018/bin/x86_64-darwin,opt/openssl/bin}
            /Library/TeX/texbin
            $HOME/.cargo/bin
            /opt/homebrew/bin
            $path
        )
        export LDFLAGS="-L/usr/local/opt/llvm/lib -L/usr/local/opt/openssl/lib -Wl,-rpath,/usr/local/opt/llvm/lib"
        export CPPFLAGS="-I/usr/local/opt/openssl/include"
        export CXXFLAGS="-I/usr/local/opt/llvm/include -I/usr/local/opt/llvm/include/c++/v1/"
        export PKG_CONFIG_PATH="/usr/local/opt/openssl/lib/pkgconfig"
        export CC=clang
        export CXX=clang++
        export ASAN_OPTIONS="detect_leaks=1"

        export clash_socks="${POISSON_IP}:7891"
        ;;
    linux*)
        path=(
            $path
        )
        export SHELL='/usr/bin/zsh'
        ;;
esac

path=(
    $HOME/.yarn/bin
    $HOME/.config/yarn/global/node_modules/.bin
    $HOME/.dotnet/tools
    $HOME/.local/bin
    $path
)

path=(
    $path
    /usr/local/{bin,sbin}
    /usr/{bin,sbin}
    /{bin,sbin}
)

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
#export LESS='-F -g -i -M -R -S -w -X -z-4'
export LESS="-i -M -R -w -z-4"

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Tmux
#
# Set the tmux socket directory
mkdir -p $HOME/.cache/tmux
export TMUX_TMPDIR=$HOME/.cache/tmux

#
# Misc
#
export LSCOLORS='ExgxcxdxdxGxDxabagacad'
export LS_COLORS='di=1;34:ln=36:so=32:pi=33:ex=33:bd=1;36:cd=1;33:su=30;41:sg=30;46:tw=30;42:ow=30;43'
export GRADLE_USER_HOME=$HOME/.cache/gradle
export GREP_COLOR='1;35;40'
export GREP_COLORS='mt=1;35;40'
export DOTNET_CLI_TELEMETRY_OPTOUT=1
