#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ -f /etc/zsh/zshenv ]]; then
    source /etc/zsh/zshenv
fi

if [[ -f "$HOME/.zprofile" ]]; then
    source "$HOME/.zprofile"
fi
