# Path to your oh-my-zsh installation.
export ZSH=$HOME/.dotfiles/oh-my-zsh
export ZSH_CUSTOM=$HOME/.dotfiles/zsh
export ZSH_COMPDUMP=$HOME/.cache/.zcompdump

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="bernoulli"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Plugins
plugins=(
    autojump
    git
    git-extras
    gitfast
    git-auto-fetch
    history-substring-search
    thefuck
    vi-mode
    fast-syntax-highlighting
    zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh

#
# User configuration
#

if [[ -f ~/.zshenv ]]; then
    source ~/.zshenv
fi

# Customized settings
if [ -f ~/.zshrc.local ]; then
    source ~/.zshrc.local
fi

# Aliases
if [ -f ~/.aliases ]; then
    source ~/.aliases
fi

bindkey -e

#
# Plugin settings
#

# Autojump
case "$OSTYPE" in
    darwin*)
        [[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh
        ;;
    linux*)
        [[ -s /usr/share/autojump/autojump.sh ]] && . /usr/share/autojump/autojump.sh
        ;;
esac

# history-substring-search
bindkey "^P" history-beginning-search-backward
bindkey "^N" history-beginning-search-forward

# autosuggestions
bindkey -M viins "^F" vi-forward-word
bindkey -M viins "^E" vi-add-eolbindkey

# completion
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
