#!/bin/zsh

apt-get install python3-dev

git clone https://github.com/vim/vim.git /root/vim
cd /root/vim

make clean
make uninstall

./configure --with-features=huge \
                    --enable-multibyte \
                    --enable-rubyinterp=yes \
                    --enable-python3interp=yes \
                    --with-python3-config-dir=/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu/ \
                    --enable-perlinterp=yes \
                    --enable-luainterp=yes \
                    --enable-gui=gtk2 \
                    --enable-cscope \
                    --prefix=/usr/local

make -j
make install
