#!/bin/zsh

if [[ "$OSTYPE" == 'linux-gnu'* ]]; then
    curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.appimage
    chmod u+x nvim-linux-x86_64.appimage
    mv nvim-linux-x86_64.appimage $HOME/.local/bin/nvim
elif [[ "$OSTYPE" == "darwin"* ]]; then
    brew install neovim
fi

pip install -U pip
python3 -m pip install --upgrade pynvim

source ~/.aliases
vi --noplugin +PlugUpgrade +PlugClean! +PlugInstall +PlugUpdate +qa!
vi +TSUpdate +CocUpdate +qa!
