#!/bin/zsh

mkdir -p ~/.local/share/fonts
for type in Bold Light Regular Retina; do
    wget -O ~/.local/share/fonts/FiraCode-${type}.ttf \
        https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/FiraCode/${type}/complete/Fira%20Code%20${type}%20Nerd%20Font%20Complete.ttf\?raw\=true;
done

fc-cache -f
