#!/bin/zsh

if [[ $# -eq 1 ]]; then
    UTILS_DIR=$1
else
    UTILS_DIR="/home/qdu/projects/jl-utils"
fi

julia $UTILS_DIR/uninstall.jl
julia -e 'using UpdateJulia; update_julia(systemwide=false, migrate_packages=:force)'
julia -e 'using Pkg; Pkg.resolve(); Pkg.update(); Pkg.instantiate()'
julia $UTILS_DIR/install.jl
julia -e 'using IJulia; IJulia.installkernel("Julia", env=Dict("JULIA_NUM_THREADS" => "$(Sys.CPU_THREADS - 8)",))'
